### ISSUE TITLE
Deadline Timer

### ISSUE THREAD

**Issue by SeaFilmz** [CommunityFocus/CommunityFocus#67]
Sometimes people can get too wrapped up into doing pomodoros and forget they have other things to do or events to go to. I suggest Community Focus has a deadline timer where you put in a time you do not want to work past that day because you have other things going on that day. The feature would be personal to each user of the group timer and notify you of when you have to leave the group pomodoro.

**Comment by intelagense** [comment]
I styled up a possible implementation in JSPaint
![Countdown timer with a second smaller countdown timer and label for a specific deadline that occurs soon](https://github.com/CommunityFocus/CommunityFocus/assets/18331781/6cd862d8-b466-4250-9ce7-7041458cd9df)
This mini, secondary countdown timer can run alongside the work timer. It can be normally hidden but become visible within a certain time frame(~15 minutes) of being due to cut down on distraction. This should only affect the current user who has set a deadline limit and should play a separate alarm and show some sort of visible alert as well.

**Comment by nmpereira** [comment]
Closing as not done because I don't feel like it adds significant value to the app.
